
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./assets/models:/app/assets/models:ro
      - ./assets/documents:/app/assets/documents:ro
    env_file:
      - .env
    networks:
      - app_network
    environment:
      - REDIS_SSL=${REDIS_SSL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      #- litellm
      - redis
      - qdrant


  frontend:
      build:
        context: .
        dockerfile: ui/Dockerfile
      restart: unless-stopped
      ports:
        - "8501:8501"
      environment:
        - BACKEND_URL=http://server:8000
      networks:
        - app_network


  qdrant:
      image: qdrant/qdrant:latest
      volumes:
        - qdrant_data:/qdrant/storage
      ports:
        - "6333:6333"  # HTTP
        - "6334:6334"  # gRPC
      networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass myredissecret
    environment:
      - REDIS_URL=  ${REDIS_URL:-redis://:myredissecret@redis:6379}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  qdrant_data:
    driver: local
  chat_history:
    driver: local
